spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moviedb
    username: postgres
    password: 1234
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

poster:
  upload-dir: ./uploads

server:
  port: 8082
  forward-headers-strategy: framework

feign:
  hystrix:
    enabled: true

swagger:
  title: Movie Service
  description: Movie Service with postgres database connection.
  version: 1.0.0

info:
  app:
    description: Service for retrieving information about movies.
    version: 1.0.0
