version: "3.2"

networks:
  back:
  front:
  management:
    external: true

volumes:
  moviedb:
  ratingdb:
  userdb:

services:
  discoverytest:
    image: ks10096/discovery-server
    build: ../discovery-server/
    restart: always
    env_file: ./.env
    environment:
      - SPRING_PROFILES_ACTIVE=${ACTIVE_PROFILE}
      - DISCO_SERVICE_NAME=${DISCOVERY_NAME}
    networks:
      - back
      - management
    labels:
      pl.polsl.student.name: "eureka-discovery-server"
      pl.polsl.student.systembelongto.name: "test1system"

      pl.polsl.student.type: "infra"
      pl.polsl.student.type.infra: "ms"
      pl.polsl.student.type.infra.subtype: "discovery"

    deploy:
      resources:
        limits:
          memory: 350M

  config-server:
    image: ks10096/config-server
    build: ../config-server/
    restart: always
    env_file: ./.env
    environment:
      - EUREKA_URI=http://${DISCOVERY_NAME}:${DISCOVERY_PORT}/eureka
      - SPRING_SECURITY_USER_NAME=${CONFIG_SERVER_USR}
      - SPRING_SECURITY_USER_PASSWORD=${CONFIG_SERVER_PWD}
      - SPRING_PROFILES_ACTIVE=${ACTIVE_PROFILE},native
    networks:
      - back
      - management
    depends_on:
      - discoverytest
    volumes:
      - type: bind
        source: ./configs
        target: /app/config
    labels:
      pl.polsl.student.name: "cloud-config-server"
      pl.polsl.student.systembelongto.name: "test1system"

      pl.polsl.student.type: "infra"
      pl.polsl.student.type.infra: "ms"
      pl.polsl.student.type.infra.subtype: "config"

    deploy:
      resources:
        limits:
          memory: 350M

  apigateway:
    image: ks10096/edge-server
    build: ../edge-service/
    restart: always
    env_file: ./.env
    environment:
      - EUREKA_URI=http://${DISCOVERY_NAME}:${DISCOVERY_PORT}/eureka
      - CONFIG_SERVER_USER=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PASSWORD=${CONFIG_SERVER_PWD}
      - SPRING_PROFILES_ACTIVE=${ACTIVE_PROFILE}
      - MOVIE_CLIENT=movieclient:80
    networks:
      front:
      back:
      management:
    ports:
      - "9080:8080"
    depends_on:
      - discoverytest
    labels:
      pl.polsl.student.name: "zuul-proxy-server"
      pl.polsl.student.systembelongto.name: "test1system"

      pl.polsl.student.type: "infra"
      pl.polsl.student.type.infra: "ms"
      pl.polsl.student.type.infra.subtype: "apigateway"

    deploy:
      resources:
        limits:
          memory: 350M

  movieclient:
    image: ks10096/movies-api-client
    build: ../movies-api-client
    networks:
      management:
      front:
    deploy:
      resources:
        limits:
          memory: 1000M
    labels:
      pl.polsl.student.name: "movies-api-client"
      pl.polsl.student.systembelongto.name: "test1system"

      pl.polsl.student.type: "dom"
      pl.polsl.student.type.dom: "gui"

  userCatalog:
    image: ks10096/user-movies-catalog-service
    build: ../user-movies-catalog-service/
    restart: always
    env_file: ./.env
    environment:
      - EUREKA_URI=http://${DISCOVERY_NAME}:${DISCOVERY_PORT}/eureka
      - SPRING_PROFILES_ACTIVE=${ACTIVE_PROFILE}
      - CONFIG_SERVER_USER=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PASSWORD=${CONFIG_SERVER_PWD}
    networks:
      - back
      - management
    depends_on:
      - discoverytest
      - config-server
    labels:
      pl.polsl.student.name: "user-movies-catalog-service"
      pl.polsl.student.systembelongto.name: "test1system"

      pl.polsl.student.type: "dom"
      pl.polsl.student.type.dom: "ms"

    deploy:
      resources:
        limits:
          memory: 350M

  movies:
    image: ks10096/movie-service
    build: ../movie-service/
    restart: always
    env_file: ./.env
    environment:
      - EUREKA_URI=http://${DISCOVERY_NAME}:${DISCOVERY_PORT}/eureka
      - SPRING_PROFILES_ACTIVE=${ACTIVE_PROFILE}
      - DB_SERVER=movieDb
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_MOVIE_DB}
      - CONFIG_SERVER_USER=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PASSWORD=${CONFIG_SERVER_PWD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${ddl_auto}
      - DATA_FILE=/app/data_file.json
    networks:
      - back
      - management
    depends_on:
      - discoverytest
      - config-server
      - movieDb
    volumes:
      - ./uploadsVolume:/app/uploads
      - type: bind
        source: ./movies_data_file.json
        target: /app/data_file.json
    labels:
      pl.polsl.student.name: "movie-service"
      pl.polsl.student.systembelongto.name: "test1system"

      pl.polsl.student.type: "dom"
      pl.polsl.student.type.dom: "ms"

    deploy:
      resources:
        limits:
          memory: 350M

  ratings:
    image: ks10096/rating-service
    build: ../rating-service/
    restart: always
    env_file: ./.env
    environment:
      - EUREKA_URI=http://${DISCOVERY_NAME}:${DISCOVERY_PORT}/eureka
      - SPRING_PROFILES_ACTIVE=${ACTIVE_PROFILE}
      - DB_SERVER=ratingDb
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_RATING_DB}
      - CONFIG_SERVER_USER=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PASSWORD=${CONFIG_SERVER_PWD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${ddl_auto}
      - DATA_FILE=/app/data_file.json
    networks:
      - back
      - management
    volumes:
      - type: bind
        source: ./ratings_data_file.json
        target: /app/data_file.json
    depends_on:
      - discoverytest
      - config-server
      - ratingDb
    labels:
      pl.polsl.student.name: "ratings-service"
      pl.polsl.student.systembelongto.name: "test1system"

      pl.polsl.student.type: "dom"
      pl.polsl.student.type.dom: "ms"

    deploy:
      resources:
        limits:
          memory: 350M

  users:
    image: ks10096/user-service
    build: ../user-service
    restart: always
    env_file: ./.env
    environment:
      - EUREKA_URI=http://${DISCOVERY_NAME}:${DISCOVERY_PORT}/eureka
      - SPRING_PROFILES_ACTIVE=${ACTIVE_PROFILE}
      - DB_SERVER=userDb
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_USER_DB}
      - CONFIG_SERVER_USER=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PASSWORD=${CONFIG_SERVER_PWD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${ddl_auto}
    networks:
      - back
      - management
    depends_on:
      - discoverytest
      - userDb
    labels:
      pl.polsl.student.name: "user-service"
      pl.polsl.student.systembelongto.name: "test1system"

      pl.polsl.student.type: "dom"
      pl.polsl.student.type.dom: "ms"

    deploy:
      resources:
        limits:
          memory: 350M

  converter:
    image: ks10096/converter-service
    build: ../converter-service
    restart: always
    env_file: ./.env
    environment:
      - EUREKA_URI=http://${DISCOVERY_NAME}:${DISCOVERY_PORT}/eureka
      - SPRING_PROFILES_ACTIVE=${ACTIVE_PROFILE}
      - CONFIG_SERVER_USER=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PASSWORD=${CONFIG_SERVER_PWD}
    networks:
      - back
      - management
    depends_on:
      - discoverytest
    labels:
      pl.polsl.student.name: "converter-service"
      pl.polsl.student.systembelongto.name: "test1system"

      pl.polsl.student.type: "dom"
      pl.polsl.student.type.dom: "ms"

    deploy:
      resources:
        limits:
          memory: 350M

  movieDb:
    image: postgres:alpine
    restart: always
    volumes:
      - moviedb:/var/lib/postgresql/data:rw
      - ./init_moviedb.sql:/docker-entrypoint-initdb.d/init.sql
    env_file: ./.env
    environment:
      - POSTGRES_DB=${POSTGRES_MOVIE_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data
    networks:
      - back
    deploy:
      resources:
        limits:
          memory: 1000M
    labels:
      pl.polsl.student.name: "postgres-movie-database"
      pl.polsl.student.systembelongto.name: "test1system"

      pl.polsl.student.type: "dom"
      pl.polsl.student.type.dom: "db"

  ratingDb:
    image: postgres:alpine
    restart: always
    volumes:
      - ratingdb:/var/lib/postgresql/data:rw
      - ./init_ratingdb.sql:/docker-entrypoint-initdb.d/init.sql
    env_file: ./.env
    environment:
      - POSTGRES_DB=${POSTGRES_RATING_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data
    networks:
      - back
    deploy:
      resources:
        limits:
          memory: 1000M
    labels:
      pl.polsl.student.name: "postgres-rating-database"
      pl.polsl.student.systembelongto.name: "test1system"

      pl.polsl.student.type: "dom"
      pl.polsl.student.type.dom: "db"

  userDb:
    image: postgres:alpine
    restart: always
    volumes:
      - userdb:/var/lib/postgresql/data:rw
      - ./init_userdb.sql:/docker-entrypoint-initdb.d/init.sql
    env_file: ./.env
    environment:
      - POSTGRES_DB=${POSTGRES_USER_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data
    networks:
      - back
    deploy:
      resources:
        limits:
          memory: 1000M
    labels:
      pl.polsl.student.name: "postgres-user-database"
      pl.polsl.student.systembelongto.name: "test1system"

      pl.polsl.student.type: "dom"
      pl.polsl.student.type.dom: "db"
