create sequence bootstrapentries_id_seq;

alter sequence bootstrapentries_id_seq owner to postgres;

create sequence hibernate_sequence;

alter sequence hibernate_sequence owner to postgres;

create table bootstrapentries
(
    id    bigint generated by default as identity
        constraint bootstrapentries_pkey
            primary key,
    label integer not null
);

alter table bootstrapentries
    owner to postgres;

create table if not exists ratings
(
	id bigint not null
		constraint ratings_pkey
			primary key,
	movie_id bigint,
	rating double precision,
	user_id bigint
);

alter table ratings owner to postgres;