global:
  scrape_interval: 5s
  external_labels:
    monitor: "my-monitor"
rule_files:
  - "alert.rules"
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["192.168.254.112:9090"]

  - job_name: "dynamic"
    file_sd_configs:
      - files:
          - "/etc/prometheus/targets.json"
        refresh_interval: 30s
