
#spring:
#  application:
#    name: user-service
#  datasource:
#    url: jdbc:postgresql://localhost:5432/userdb
#    username: postgres
#    password: 1234
#    driver-class-name: org.postgresql.Driver
#    hikari:
#      minimum-idle: 0
#      maximum-pool-size: 15
#      connection-timeout: 10000
#      idle-timeout: 300000
#      max-lifetime: 600000
#      initialization-fail-timeout: -1
#      validation-timeout: 1000
#    continue-on-error: true
#  jpa:
#    open-in-view: false
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    shutdown:
#      enabled: true
#    health:
#      show-details: always
#
#
#swagger:
#  title: User Service
#  description: Service containing users.
#  license: License
#  licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
#  version: 0.1
#  contact:
#    name: Kamil Socha
#    url:
#    email: kamisoc782@student.polsl.pl
#
#info:
#  app:
#    name: ${spring.application.name}
#    description: Eureka Discovery Server for microservices system.
#    version: 0.1.0
#  developer:
#    name: Kamil Socha
#    email: kamisoc782@student.polsl.pl
##spring:
##  application:
##    name: user-service
##  datasource:
##    url: jdbc:postgresql://localhost:5432/userdb
##    username: postgres
##    password: 1234
##  jpa:
##    hibernate:
##      ddl-auto: update
##
#server:
#  port: 9061
#
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
##
##management:
##  endpoints:
##    web:
##      exposure:
##        include: "*"
##  endpoint:
##    shutdown:
##      enabled: true
##    health:
##      show-details: always
##
##swagger:
##  title: User Service
##  description: Service containing users.
##  license: License
##  licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
##  version: 0.1
##  contact:
##    name: Kamil Socha
##    url:
##    email: kamisoc782@student.polsl.pl
##
##info:
##  app:
##    name: ${spring.application.name}
##    description: Eureka Discovery Server for microservices system.
##    version: 0.1.0
##  developer:
##    name: Kamil Socha
##    email: kamisoc782@student.polsl.pl
##
##---
##spring:
##  profiles: docker
##  cloud:
##    loadbalancer:
##      ribbon:
##        enabled: false #??
##  datasource:
##    url: jdbc:postgresql://${DB_SERVER}:5432/${POSTGRES_DB}
##    username: ${POSTGRES_USER}
##    password: ${POSTGRES_PASSWORD}
##
##server:
##  port: 8080
##
##eureka:
##  instance:
##    hostname: user-service
##    prefer-ip-address: true
##  client:
##    service-url:
##      defaultZone: http://discovery:8761/eureka/
