server:
  port: 8081

swagger:
  title: Converter Service
  description: Service converting Roman Numbers to Decimal and reversed.

info:
  app:
    description: Converter Service.
    version: 1.0.0
