spring:
  datasource:
    url: jdbc:postgresql://${DB_SERVER}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
      # ddl-auto: create

poster:
  upload-dir: /app/uploads

server:
  port: 8080
  forward-headers-strategy: framework
