spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ratingdb
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always

swagger:
  title:  Rating Service
  description: Rating service with postgres database connection.
  version: 1.0.0

info:
  app:
    description: Service for retrieving information about ratings of movies.
    version: 1.0.0
