server:
  port: 8085

feign:
  hystrix:
    enabled: true

ribbon:
  eureka:
    enabled: true
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
  ReadTimeout: 500

hystrix:
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 5
        errorThresholdPercentage: 50
        sleepWindowInMilliseconds: 5000
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
      metrics:
        rollingStats:
          timeInMilliseconds: 20000

swagger:
  title:  User Movies Catalog Service
  description: Netflix Eureka Discovery Server for microservices system.
  version: 1.0.0

info:
  app:
    description: Eureka Discovery Server for microservices system.
    version: 1.0.0
