create sequence if not exists bootstrapentries_id_seq;
--
-- alter sequence bootstrapentries_id_seq owner to postgres;
--
create sequence if not exists hibernate_sequence;
--
-- alter sequence hibernate_sequence owner to postgres;

create table if not exists bootstrapentries
(
    id    bigint generated by default as identity
        constraint bootstrapentries_pkey
            primary key,
    label integer not null
);

-- alter table bootstrapentries
--     owner to postgres;

create table if not exists movies
(
    id          bigint not null
        constraint movies_pkey
            primary key,
    description varchar(255),
    director    varchar(255),
    name        varchar(255)
        constraint uk_need1sfwodvn2yjle40es9twm
            unique,
    poster_uri  varchar(255)
);

-- alter table movies
--     owner to postgres;

