#spring:
#  profiles:
#    active: native
#  application:
#    name: config-server
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/configs
#  security:
#    user:
#      name: ${CONFIG_SERVER_USERNAME}
#      password: ${CONFIG_SERVER_PASSWORD}
#
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaulZone: http://localhost:8761/eureka/
#
#server:
#  port: 8888
#
#management:
#  endpoint:
#    health:
#      show-details: always
#
#---
#spring:
#  profiles: docker
#
#eureka:
#  instance:
#    hostname: config-server
#    prefer-ip-address: true
#  client:
#    serviceUrl:
#      defaultZone: http://discovery:8761/eureka/
